from abc import ABC, abstractmethod
from typing import Optional, Protocol, Sequence
from uuid import UUID

from app.domain.entities.base import ContentEntity


class ContentSlugRegistryPort(ABC):
    @abstractmethod
    async def reserve(self, slug: str, content_id: UUID, content_kind: str) -> None: ...

    @abstractmethod
    async def assert_available(self, slug: str, excluding_content_id: Optional[UUID] = None) -> None: ...

    @abstractmethod
    async def release(self, slug: str, content_id: UUID) -> None: ...


class CourseRepositoryPort(Protocol):
    async def create(self, course: ContentEntity) -> ContentEntity: ...
    async def get_by_id(self, course_id: UUID) -> Optional[ContentEntity]: ...
    async def get_by_slug(self, slug: str) -> Optional[ContentEntity]: ...
    async def get_hierarchy(self, course_id: UUID, include_archived: bool = False) -> Optional[ContentEntity]: ...
    async def update(self, course: ContentEntity) -> ContentEntity: ...
    async def delete(self, course_id: UUID) -> bool: ...


class ModuleRepositoryPort(Protocol):
    async def create(self, module: ContentEntity) -> ContentEntity: ...
    async def get_by_id(self, module_id: UUID) -> Optional[ContentEntity]: ...
    async def list_by_course(self, course_id: UUID, include_archived: bool = False) -> Sequence[ContentEntity]: ...
    async def update(self, module: ContentEntity) -> ContentEntity: ...
    async def delete(self, module_id: UUID) -> bool: ...


class SectionRepositoryPort(Protocol):
    async def create(self, section: ContentEntity) -> ContentEntity: ...
    async def get_by_id(self, section_id: UUID) -> Optional[ContentEntity]: ...
    async def get_hierarchy(self, section_id: UUID) -> Optional[ContentEntity]: ...
    async def list_by_module(self, module_id: UUID, include_archived: bool = False) -> Sequence[ContentEntity]: ...
    async def update(self, section: ContentEntity) -> ContentEntity: ...
    async def delete(self, section_id: UUID) -> bool: ...
