"""Ports consumed by quiz-assessment application use cases."""

from typing import Protocol
from uuid import UUID

from app.domain.entities.question import Question
from app.domain.entities.quiz import Quiz
from app.domain.entities.quiz_sitting import QuizSitting
from app.domain.entities.quiz_sitting_snapshot import QuizSittingQuestionSnapshot, QuizSittingResult


class QuizAssessmentRepositoryPort(Protocol):
    async def get_by_id(self, quiz_id: UUID) -> Quiz | None: ...
    async def list_questions(self, quiz_id: UUID) -> list[Question]: ...
    async def list_answers(self, question: Question): ...
    async def create_question(self, question: Question) -> Question: ...
    async def update_question(self, question: Question) -> Question: ...
    async def update_quiz(self, quiz: Quiz) -> Quiz: ...


class QuizSittingRepositoryPort(Protocol):
    async def get_by_id(self, sitting_id: UUID) -> QuizSitting | None: ...
    async def get_active(self, quiz_id: UUID, learner_id: str) -> QuizSitting | None: ...
    async def create(self, sitting: QuizSitting) -> QuizSitting: ...
    async def save_snapshot(self, snapshots: list[QuizSittingQuestionSnapshot]) -> None: ...
    async def get_snapshot(self, sitting_id: UUID) -> list[QuizSittingQuestionSnapshot]: ...
    async def replace_selection(self, sitting_question_id: UUID, option_ids: set[UUID]) -> None: ...
    async def selected_option_ids(self, sitting_id: UUID) -> dict[UUID, set[UUID]]: ...
    async def save_final_result(self, sitting: QuizSitting, result: QuizSittingResult) -> None: ...
    async def get_final_result(self, sitting_id: UUID) -> QuizSittingResult | None: ...
    async def list_final_results(self, quiz_id: UUID, learner_id: str) -> list[QuizSittingResult]: ...
    async def reserve_exam_finalization(self, quiz_id: UUID, learner_id: str, max_attempts: int) -> None: ...
