"""add sequence course

Revision ID: 0010_add_sequence_course
Revises: 0009_course_enrollment
Create Date: 2026-09-28 23:08:48.060582
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0010_add_sequence_course'
down_revision: Union[str, None] = '0009_course_enrollment'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('sequence', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'sequence')
    # ### end Alembic commands ###
